services:
  redis:
    image: redis:7.2
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis_data: