services:
  redis:
    image: redis:7.2
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quarkus-langchain-ai
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  redis_data:
  mysql_data: